# TrajectoryPlannerROS:
TebLocalPlannerROS:
  odom_topic:                                  /odom
  map_frame:                                   /map

  # Trajectory
  teb_autosize:                                True
  dt_ref:                                      0.3
  dt_hysteresis:                               0.1
  global_plan_overwrite_orientation:           True
  max_global_plan_lookahead_dist:              3.0
  # feasibility_check_no_poses:                5
  feasibility_check_no_poses:                  30

  # Robot

  # max_vel_x:                                   0.4
  # max_vel_x_backwards:                         0.2
  # max_vel_theta:                               0.3
  max_vel_x:                                   1.0
  max_vel_x_backwards:                         1.0
  max_vel_theta:                               1.0
  acc_lim_x:                                   0.25
  acc_lim_theta:                               0.5
  min_turning_radius:                          0.0
  footprint_model: # types:                    "point", "circular", "two_circles", "line", "polygon"
    type:                                      "polygon"
    vertices:                                  [ [-0.20, -0.2], [-0.27, -0.15], [-0.27, 0.15], [-0.20, 0.2], [0.07, 0.2],  [0.19, 0.05], [0.19, -0.05], [0.07, -0.2] ]
    # type:                                    "circular"
    # radius:                                  0.2
    # vertices:                                [[0.20, 0.20], [0.20, -0.20], [-0.30, -0.20], [-0.30, 0.20]]

  # GoalTolerance

  # xy_goal_tolerance:                           0.2
  # yaw_goal_tolerance:                          0.1
  #10cm
  xy_goal_tolerance:                           0.1
  #5deg
  yaw_goal_tolerance:                          0.1
  free_goal_vel:                               False

  # global_plan_viapoint_sep:                  0.5

  # Obstacles

  # min_obstacle_dist:                         0.05
  min_obstacle_dist:                           0.025
  # min_obstacle_dist:                         0.001
  # inflation_dist:                            0.1
  inflation_dist:                              0.05
  include_costmap_obstacles:                   True
  # include_costmap_obstacles:                 False
  costmap_obstacles_behind_robot_dist:         0.3
  # obstacle_poses_affected:                   30
  obstacle_poses_affected:                     10
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor:          1.1

  costmap_converter_plugin:                    ""
  costmap_converter_spin_thread:               True
  costmap_converter_rate:                      5

  obstacle_cost_exponent:                      4.0

  # Optimization

  no_inner_iterations:                         5
  no_outer_iterations:                         4
  optimization_activate:                       True
  optimization_verbose:                        False
  # penalty_epsilon:                           0.1
  # penalty_epsilon:                           0.05
  penalty_epsilon:                             0.025
  # penalty_epsilon:                           0.001
  weight_max_vel_x:                            2
  weight_max_vel_theta:                        1
  weight_acc_lim_x:                            1
  weight_acc_lim_theta:                        1
  weight_kinematics_nh:                        1000
  # weight_kinematics_forward_drive:             900
  weight_kinematics_forward_drive:             500
  # weight_kinematics_forward_drive:           1
  weight_kinematics_turning_radius:            1
  weight_optimaltime:                          1
  # weight_obstacle:                           50
  weight_obstacle:                             100
  weight_dynamic_obstacle:                     10 # not in use yet
  alternative_time_cost:                       False # not in use yet

  # Homotopy Class Planner

  enable_homotopy_class_planning:              True
  enable_multithreading:                       True
  simple_exploration:                          False
  max_number_classes:                          4
  roadmap_graph_no_samples:                    15
  roadmap_graph_area_width:                    5
  h_signature_prescaler:                       0.5
  h_signature_threshold:                       0.1
  obstacle_keypoint_offset:                    0.1
  obstacle_heading_threshold:                  0.45
  visualize_hc_graph:                          False
