BEYOND_TRAINER:
  TRAIN_MODE: True
  # TRAIN_MODE: False
  DEVICE: "cuda"
  # DEVICE: "cpu"
  # LR: 2.5e-3

  EVAL_BATCH_SIZE: 1

  #8g gpu
  # BATCH_SIZE: 4
  # ROLLOUT_SIZE: 32

  #4791MiB gpu
  # BATCH_SIZE: 4
  # ROLLOUT_SIZE: 8

  # #4791MiB gpu?
  # BATCH_SIZE: 2
  # ROLLOUT_SIZE: 16

  # #5367MiB
  # BATCH_SIZE: 2
  # ROLLOUT_SIZE: 32

  # #8705MiB
  # BATCH_SIZE: 2
  # ROLLOUT_SIZE: 64

  # #8705MiB
  # BATCH_SIZE: 2
  # ROLLOUT_SIZE: 64

  # # 11711MiB
  # BATCH_SIZE: 4
  # ROLLOUT_SIZE: 64

  # 7607MiB
  # BATCH_SIZE: 4
  # ROLLOUT_SIZE: 32

  # # # 7607MiB
  # BATCH_SIZE: 4
  # ROLLOUT_SIZE: 64

  # # 11437MiB
  BATCH_SIZE: 2
  ROLLOUT_SIZE: 64

  # 11437MiB
  # BATCH_SIZE: 2
  # ROLLOUT_SIZE: 128


  # # 7607MiB
  # BATCH_SIZE: 4
  # ROLLOUT_SIZE: 32

  # BATCH_SIZE: 2
  # ROLLOUT_SIZE: 4

  # # NUM_CHECKPOINTS: -1
  # # NUM_UPDATES: 1024
  # # NUM_UPDATES: 4096
  # NUM_UPDATES: 16384
  # NUM_CHECKPOINTS: 16
  # # NUM_CHECKPOINTS: 4
  # # NUM_CHECKPOINTS: 10
  # # CHECKPOINT_INTERVAL: 64
  # # CHECKPOINT_INTERVAL: 256
  # CHECKPOINT_INTERVAL: 1024

  # NUM_UPDATES: 1024
  # NUM_CHECKPOINTS: 4
  # CHECKPOINT_INTERVAL: 256

  # NUM_UPDATES: 4096
  # NUM_CHECKPOINTS: 4
  # CHECKPOINT_INTERVAL: 1024

  # NUM_UPDATES: 8192
  # NUM_CHECKPOINTS: 32
  # CHECKPOINT_INTERVAL: 256

  # NUM_UPDATES: 8192
  # NUM_CHECKPOINTS: 16
  # CHECKPOINT_INTERVAL: 512

  # NUM_UPDATES: 16384
  # NUM_UPDATES: 32768
  # NUM_CHECKPOINTS: 64
  # CHECKPOINT_INTERVAL: 512

  NUM_UPDATES: 65536
  NUM_CHECKPOINTS: 128
  CHECKPOINT_INTERVAL: 512

  # EXPERIMENT_NAME: "beyond_rl_lv2_small_train_reward_explore_more_smooth_with_dist_and_success"
  # EXPERIMENT_NAME: "beyond_rl_overfit"
  # EXPERIMENT_NAME: "beyond_rl_overfit_lstm"
  # EXPERIMENT_NAME: "beyond_rl_semanticEnv_circle_with_heuristic_sparse_reward"
  # EXPERIMENT_NAME: "beyond_rl_v006_habitat_with_sseg_yolact_categorical"
  EXPERIMENT_NAME: "beyond_rl_habitat_with_sseg_yolact_train_all_scenes_polar"

  LOG_DIR: "habitat-challenge-data/log/"
  CHECKPOINT_FOLDER: "habitat-challenge-data/checkpoints/"

  RESUME_TRAIN: True
  # RESUME_TRAIN: False
  # RESUME_ONLY_FEATURE_NET: True
  RESUME_ONLY_FEATURE_NET: False
  # RESUME_TRAIN: False
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/deeprl_lv0train_20_03_2021/ckpt.best.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train22-03-2021_13-31-32/ckpt.13.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_fixed_reward_and_boundary24-03-2021_14-10-24/ckpt.14.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_reward_explore_and_go_near_target25-03-2021_16-47-06/ckpt.10.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_reward_explore_more_smooth_with_dist_and_success26-03-2021_14-40-06/ckpt.2.pth"

  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_13-24-30/ckpt.2.pth"
  # RESUME_TRAIN_CHEKPOINT: "beyond_agent/checkpoints/beyond_rl_overfit_lstm27-03-2021_13-24-30_ckpt.2.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv14-04-2021_14-15-17/ckpt.last.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv14-04-2021_15-34-26/ckpt.last.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv14-04-2021_17-48-34/ckpt.last.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv14-04-2021_20-40-06/ckpt.last.pth"

  #fresh start
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/checkpoints/beyond_rl_semanticEnv15-04-2021_14-31-38/ckpt.0.pth"
  #65536 iterations
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv15-04-2021_14-31-38/ckpt.1.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv15-04-2021_21-02-34/ckpt.0.pth"
  # RESUME_TRAIN_CHEKPOINT: "beyond_agent/checkpoints/beyond_rl_overfit_lstm27-03-2021_13-24-30_ckpt.2.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_no_heurist_ddppo_blind18-04-2021_01-27-27/ckpt.0.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic18-04-2021_14-13-28/ckpt.2.pth"

  #best so far!
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic18-04-2021_17-21-00/ckpt.0.pth"

  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic_sparse_reward20-04-2021_00-13-10/ckpt.2.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic_sparse_reward20-04-2021_02-45-32/ckpt.11.pth"

  #around 0.95 success
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic_sparse_reward20-04-2021_06-04-01/ckpt.9.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v003_habitat_with_sseg_yolact_fix_direction02-05-2021_15-45-15/ckpt.6.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v004_habitat_with_sseg_yolact03-05-2021_12-36-55/ckpt.21.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v004_habitat_with_sseg_yolact_categorical04-05-2021_19-32-37/ckpt.1.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v004_habitat_with_sseg_yolact_categorical04-05-2021_19-32-37/ckpt.1.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v005_habitat_with_sseg_yolact_categorical04-05-2021_22-45-57/ckpt.1.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_03-14-28/ckpt.8.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact06-05-2021_16-07-11/ckpt.11.pth"



  #all classes
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact07-05-2021_20-58-52/ckpt.10.pth"

  #overfit
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_02-04-55/ckpt.8.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.7.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact10-05-2021_02-08-32/ckpt.best_success.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact10-05-2021_02-08-32/ckpt.3.pth"

  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact10-05-2021_20-54-48/ckpt.best_success_0_21123595505617979.pth"
  RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_habitat_with_sseg_yolact_train_all_scenes_polar11-05-2021_21-09-37/ckpt.7.pth"

  #success: 0.827 habitat train2
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_16-24-45/ckpt.2.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.10.pth"

  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v003_habitat_with_sseg_yolact02-05-2021_03-20-54/ckpt.7.pth"

  #habitat v002 first train
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt20-04-2021_19-50-17/ckpt.5.pth"

  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic_sparse_reward19-04-2021_18-18-56/ckpt.15.pth"

  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic_sparse_reward19-04-2021_13-11-19/ckpt.5.pth"


  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic18-04-2021_18-11-25/ckpt.5.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic18-04-2021_23-24-54/ckpt.9.pth"




  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_22-43-53/ckpt.6.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_22-43-53/ckpt.7.pth"
  # RESUME_TRAIN_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_22-43-53/ckpt.8.pth"


  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/ckpt.best.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train22-03-2021_13-31-32/ckpt.13.pth"

  #from scratch
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_fixed_reward_and_boundary24-03-2021_14-10-24/ckpt.14.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_reward_explore_and_go_near_target25-03-2021_16-47-06/ckpt.3.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_reward_explore_and_go_near_target25-03-2021_16-47-06/ckpt.9.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_reward_explore_and_go_near_target25-03-2021_16-47-06/ckpt.10.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_reward_explore_more_smooth_with_dist_and_success26-03-2021_14-40-06/ckpt.2.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_lv2_small_train_reward_explore_more_smooth_with_dist_and_success26-03-2021_14-40-06/ckpt.2.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_13-24-30/ckpt.2.pth"

  # RESUME_EVAL_CHEKPOINT: "beyond_agent/checkpoints/beyond_rl_overfit_lstm27-03-2021_13-24-30_ckpt.2.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_semanticEnv_circle_with_heuristic_sparse_reward20-04-2021_06-04-01/ckpt.9.pth"

  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_22-43-53/ckpt.6.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_22-43-53/ckpt.7.pth"
  # RESUME_EVAL_CHEKPOINT: "habitat-challenge-data/checkpoints/beyond_rl_overfit_lstm27-03-2021_22-43-53/ckpt.8.pth"

  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_16-24-45/ckpt.2.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.0.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.1.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.2.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.3.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.4.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.5.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.6.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.7.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.8.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.9.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.10.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.11.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.12.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.13.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.14.pth",
  # "habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.last.pth"]

  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_v002_habitat_with_sseg_gt21-04-2021_20-27-16/ckpt.10.pth",]
  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_v003_habitat_with_sseg_yolact02-05-2021_03-20-54/ckpt.6.pth",]

  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_v004_habitat_with_sseg_yolact03-05-2021_12-36-55/ckpt.21.pth",]

  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.0.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.1.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.2.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.3.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.4.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.5.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.6.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.7.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.8.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.9.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.10.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.11.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.12.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.13.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.14.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.15.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.16.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_v006_habitat_with_sseg_yolact_categorical05-05-2021_17-22-34/ckpt.17.pth",]

  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact06-05-2021_16-07-11/ckpt.11.pth",]
  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact07-05-2021_20-58-52/ckpt.10.pth",]
  #
  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.best_success.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.0.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.1.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.2.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.3.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.4.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.5.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.6.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.7.pth",
  #   "habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact09-05-2021_14-00-01/ckpt.8.pth",]

  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact10-05-2021_02-08-32/ckpt.best_success.pth",]
  # RESUME_EVAL_CHEKPOINT: ["beyond_agent/checkpoints/ckpt.best_success_0_006578947368421052.pth",
  #   "beyond_agent/checkpoints/ckpt.best_success_0_006493506493506494.pth",
  #   "beyond_agent/checkpoints/ckpt.best_success_0_006578947368421052.pth",]

  # RESUME_EVAL_CHEKPOINT: ["beyond_agent/checkpoints/ckpt.best_success_0_006493506493506494.pth",]
  #best so far
  # RESUME_EVAL_CHEKPOINT: ["beyond_agent/checkpoints/ckpt.best_success_0_006622516556291391.pth",]
  # RESUME_EVAL_CHEKPOINT: ["beyond_agent/checkpoints/ckpt.best_reward.pth",]
  # RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_no_success_habitat_with_sseg_yolact10-05-2021_20-54-48/ckpt.best_success_0_21123595505617979.pth",]


  RESUME_EVAL_CHEKPOINT: ["habitat-challenge-data/checkpoints/beyond_rl_habitat_with_sseg_yolact_train_all_scenes_polar11-05-2021_21-09-37/ckpt.7.pth",]


  USE_PREDICTION: True
  # USE_PREDICTION: False

  LOG_INTERVAL: 16

  LOAD_CHECKPOINT: True
  # LOAD_CHECKPOINT: False
  ENVIRONMENT_LIST:
    TRAIN:
      TYPE: ObjectNav-v1
      # PATH: "habitat-challenge-data/objectgoal_mp3d/"
      # NAMES: ["val_mini"]
      PATH: "habitat-challenge-data/mine_objectgoal_mp3d/"
      NAMES: ["lv2_train_small"]
      # NAMES: ["single_scene_all_classes_train"]
      # NAMES: ["single_scene_all_classes_train2"]
      # NAMES: ["single_scene_all_classes_train3_balanced"]
      # NAMES: ["single_scene_all_classes_train4_balanced"]
      # NAMES: ["single_scene_all_classes_train4_balanced_short_eps"]
      # NAMES: ["lv0_train"]
      # NAMES: ["simple"]
    EVAL:
      TYPE: ObjectNav-v1
      # PATH: "habitat-challenge-data/mine_objectgoal_mp3d/"
      PATH: "habitat-challenge-data/objectgoal_mp3d/"
      # NAMES: ["lv0_test"]
      # NAMES: ["simple"]
      # NAMES: ["single_scene_all_classes_train2"]
      # NAMES: ["single_scene_all_classes_train4_balanced_short_eps"]
      # NAMES: ["single_scene_all_classes_train4_balanced"]
      NAMES: ["val_mini"]
  PPO:
    # ppo params
    clip_param: 0.2
    # ppo_epoch: 4
    # # ppo_epoch: 8
    # num_mini_batch: 2

    ppo_epoch: 4
    # ppo_epoch: 8
    num_mini_batch: 2

    value_loss_coef: 0.5
    # entropy_coef: 0.01
    entropy_coef: 0.001
    #default
    # lr: 2.5e-4

    #new
    lr: 2.5e-5
    # lr: 2.5e-3
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 64
    # use_gae: True
    use_gae: False
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 64
    use_normalized_advantage: False
