# ENVIRONMENT:
#   USE_GT_SSEG: True
#   # USE_GT_SSEG: False
#   MAX_EPISODE_STEPS: 500
#   ITERATOR_OPTIONS:
#     SHUFFLE: False
# SIMULATOR:
#   TURN_ANGLE: 30
#   TILT_ANGLE: 30
#   ACTION_SPACE_CONFIG: "v1"
#   AGENT_0:
#     # SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
#     SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
#     HEIGHT: 0.88
#     RADIUS: 0.18
#   HABITAT_SIM_V0:
#     GPU_DEVICE_ID: 0
#     ALLOW_SLIDING: False
#     GPU_GPU: True
#   SEMANTIC_SENSOR:
#     WIDTH: 640
#     HEIGHT: 480
#     HFOV: 79
#     POSITION: [0, 0.88, 0]
#   RGB_SENSOR:
#     WIDTH: 640
#     HEIGHT: 480
#     HFOV: 79
#     POSITION: [0, 0.88, 0]
#   DEPTH_SENSOR:
#     WIDTH: 640
#     HEIGHT: 480
#     HFOV: 79
#     MIN_DEPTH: 0.5
#     MAX_DEPTH: 5.0
#     POSITION: [0, 0.88, 0]
# TASK:
#   TYPE: ObjectNav-v1
#   # POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
#   POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
#   SUCCESS_DISTANCE: 0.1
#
#   SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
#   GOAL_SENSOR_UUID: objectgoal
#
#   MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']
#   # MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'TOP_DOWN_MAP']
#
#   DISTANCE_TO_GOAL:
#     DISTANCE_TO: VIEW_POINTS
#   SUCCESS:
#     SUCCESS_DISTANCE: 0.1
#
# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val_mini
#   DATA_PATH: habitat-challenge-data/objectgoal_mp3d/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"
#
# # DATASET:
# #   TYPE: ObjectNav-v1
# #   SPLIT: lv0_train
# #   DATA_PATH: habitat-challenge-data/mine_objectgoal_mp3d/{split}/{split}.json.gz
# #   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"
#
# # DATASET:
# #   TYPE: ObjectNav-v1
# #   SPLIT: lv0_test
# #   DATA_PATH: habitat-challenge-data/mine_objectgoal_mp3d/{split}/{split}.json.gz
# #   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"
#
# # DATASET:
# #   TYPE: ObjectNav-v1
# #   SPLIT: simple
# #   DATA_PATH: habitat-challenge-data/mine_objectgoal_mp3d/{split}/{split}.json.gz
# #   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.1

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val_mini
  # SPLIT: val
  DATA_PATH: habitat-challenge-data/objectgoal_mp3d/{split}/{split}.json.gz
  SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"
