ENVIRONMENT:
  USE_GT_SSEG: True
  # USE_GT_SSEG: False

  MAX_EPISODE_STEPS: 500
  # MAX_EPISODE_STEPS: 250
  # MAX_EPISODE_STEPS: 1
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    # SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
    GPU_GPU: True
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  # POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  # MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'COLLISIONS', 'TOP_DOWN_MAP']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.1

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val_mini
#   DATA_PATH: habitat-challenge-data/objectnav_mp3d_v1/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: test_mini
#   DATA_PATH: habitat-challenge-data/objectnav_mp3d_v1/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val
#   DATA_PATH: habitat-challenge-data/objectnav_mp3d_v1/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val
#   DATA_PATH: habitat-challenge-data/objectnav_mp3d_v1/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val
#   DATA_PATH: habitat-challenge-data/val_gibson_v4_4_8m_small/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val
#   DATA_PATH: habitat-challenge-data/val_gibson_v4_4_8m_small_mp3d_to_gibson/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val
#   DATA_PATH: habitat-challenge-data/val_gibson_v4_1_2m/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val
#   DATA_PATH: habitat-challenge-data/val_gibson_v4_1_2m_mp3d_to_gibson/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

# DATASET:
#   TYPE: ObjectNav-v1
#   SPLIT: val
#   DATA_PATH: habitat-challenge-data/igibson_single_2_4m_ep_per_class_4_scenes/{split}/{split}.json.gz
#   SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val
  DATA_PATH: habitat-challenge-data/val_gibson_v4_2_4m_mp3d_to_gibson/{split}/{split}.json.gz
  SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"
